### ISSUE TITLE
Selecting fahrenheiht doesn't change the scale

### ISSUE THREAD

**Issue by robmarkcole** [veit/flask-bokeh-dashboard#3]
As title, 

![image](https://user-images.githubusercontent.com/11855322/63487010-9465f780-c4a1-11e9-8cfb-cd0ae2ecb6bf.png)

**Comment by veit** [comment]
Yes I know  ;-)
I just wanted to provide a lightweight example of how Flask can affect the rendering of the bokeh plot. I should clarify this in the README. Thanks for the hint!
